FROM golang:1.10-alpine

RUN mkdir -p /go/src/app
WORKDIR /go/src/app

RUN apk add --no-cache git gcc musl-dev

RUN go get github.com/codegangsta/gin

EXPOSE 8080

CMD ["gin", "--port", "8080", "--appPort", "8081", "run", "*.go"]

RUN go get github.com/NYTimes/gziphandler && \
    go get github.com/lib/pq && \
    go get github.com/golang-migrate/migrate && \
    go get github.com/gorilla/sessions
