version: '3'

services:
  db:
    image: postgres:10.4-alpine
    environment:
      POSTGRES_PASSWORD: example
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "./frontend/src:/usr/src"
      - "./frontend/public:/usr/public"
    depends_on:
      - backend
    ports:
      - "3000:3000"
    tty: true

  backend:
    build:
      context: .
      dockerfile: Dockerfile.go-dev
    volumes:
      - "./backend/:/go/src/app"
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      - PG_HOST=db
      - PG_DBNAME=postgres
      - PG_USER=postgres
      - PG_PASSWORD=example
      - PG_SSL_MODE=disable

volumes:
  pgdata:
